// RabbitMQ Management HTTP API MCP server — generated by mcpify. Do not hand-edit.
//
// Interactive setup wizard (REQ-1.6): collects the API URL and the
// credentials the discovered auth scheme(s) need, then persists them per
// the operator's choice: a .env file, a config.json file, or a
// ready-to-run CLI invocation printed to stdout (nothing written to disk).
// `inquire`'s prompts are blocking — run through `spawn_blocking`, the
// same pattern mcpify's own `auth_profile::prompt` documents for calling
// it from an async runtime.

use std::collections::HashMap;
use std::path::PathBuf;
use std::time::Duration;

use serde_json::{Map, Value};

use rabbitmq_mcp::core::config_schema::{AuthMethod, Transport};
use rabbitmq_mcp::core::credential_storage::save_credential;

/// Resolves the home directory the same way `core::config_manager` does
/// (`HOME` then `USERPROFILE` then `.`) so the wizard's "global" choice
/// writes to exactly the path the runtime loader reads back from.
fn home_dir() -> PathBuf {
    std::env::var_os("HOME")
        .or_else(|| std::env::var_os("USERPROFILE"))
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."))
}

fn to_env_key(key: &str) -> String {
    key.to_uppercase()
}

async fn prompt_base_url() -> anyhow::Result<String> {
    let url = tokio::task::spawn_blocking(|| {
        inquire::Text::new("RabbitMQ Management HTTP API base URL:").prompt()
    })
    .await??;

    let client = reqwest::Client::new();
    match client
        .head(&url)
        .timeout(Duration::from_secs(5))
        .send()
        .await
    {
        Ok(_) => println!("reachable"),
        Err(_) => println!(
            "could not reach that URL yet — continuing anyway (fix it later with `test-connection`)"
        ),
    }

    Ok(url)
}

async fn prompt_auth_method() -> anyhow::Result<AuthMethod> {
    // Exactly one scheme was discovered — nothing to choose between.
    Ok(AuthMethod::Basic)
}

// mcpify:versions:begin
async fn prompt_api_version() -> anyhow::Result<String> {
    let choices = vec![
        "4.3.2 (default/latest)",
        "4.2.8",
        "4.1.8",
        "4.0.9",
        "3.13.7",
    ];
    let selection = tokio::task::spawn_blocking(move || {
        inquire::Select::new("API version to use:", choices).prompt()
    })
    .await??;

    Ok(match selection {
        "4.3.2 (default/latest)" => "4.3.2".to_string(),
        "4.2.8" => "4.2.8".to_string(),
        "4.1.8" => "4.1.8".to_string(),
        "4.0.9" => "4.0.9".to_string(),
        "3.13.7" => "3.13.7".to_string(),
        other => other.to_string(),
    })
}
// mcpify:versions:end

async fn prompt_transport() -> anyhow::Result<Transport> {
    let choices = vec![
        "stdio (spawned as a subprocess by the MCP client)",
        "http (a standalone server the MCP client connects to over the network)",
    ];
    let selection = tokio::task::spawn_blocking(move || {
        inquire::Select::new("Which transport will this deployment use?", choices).prompt()
    })
    .await??;

    Ok(if selection.starts_with("stdio") {
        Transport::Stdio
    } else {
        Transport::Http
    })
}

async fn prompt_credentials(auth_method: AuthMethod) -> anyhow::Result<HashMap<String, String>> {
    tokio::task::spawn_blocking(move || -> anyhow::Result<HashMap<String, String>> {
        let mut credentials = HashMap::new();
        match auth_method {
            AuthMethod::Basic => {
                credentials.insert(
                    "username".to_string(),
                    inquire::Text::new("Username:").prompt()?,
                );
                credentials.insert(
                    "password".to_string(),
                    inquire::Password::new("Password:")
                        .without_confirmation()
                        .prompt()?,
                );
            }
        }
        Ok(credentials)
    })
    .await?
}

/// Persists settings per the operator's choice (Fix 5): a config *file* now
/// means the exact YAML file/path/key-shape `core::config_manager::load_config`
/// actually reads back — either the local-cwd file it checks first
/// (`./rabbitmq-mcp.config.yml`) or the global home-dir file it checks next
/// (`~/.rabbitmq-mcp/config.yml`) — using flat, unprefixed keys (`url`,
/// `auth_method`, `api_version`, `transport`, ...) matching `env_overrides`'s
/// `config_key` column, not the `RABBITMQ_MCP_`-prefixed env-var names.
/// `config_fields` intentionally excludes credentials — those stay on the
/// `save_credential`/keychain path and are never written to this file.
async fn prompt_persistence(
    config_fields: &Map<String, Value>,
    env: &HashMap<String, String>,
) -> anyhow::Result<()> {
    let choices = vec![
        "Write a local config file (./rabbitmq-mcp.config.yml)",
        "Write a global config file (~/.rabbitmq-mcp/config.yml)",
        "Print a ready-to-run CLI invocation (nothing written to disk)",
    ];
    let selection = tokio::task::spawn_blocking(move || {
        inquire::Select::new("How should these settings be saved?", choices).prompt()
    })
    .await??;

    match selection {
        "Write a local config file (./rabbitmq-mcp.config.yml)" => {
            let yaml = serde_yaml::to_string(config_fields)?;
            std::fs::write("rabbitmq-mcp.config.yml", yaml)?;
            println!("Wrote ./rabbitmq-mcp.config.yml");
        }
        "Write a global config file (~/.rabbitmq-mcp/config.yml)" => {
            let dir = home_dir().join(".rabbitmq-mcp");
            std::fs::create_dir_all(&dir)?;
            let path = dir.join("config.yml");
            let yaml = serde_yaml::to_string(config_fields)?;
            std::fs::write(&path, yaml)?;
            println!("Wrote {}", path.display());
        }
        _ => {
            let flags = env
                .iter()
                .map(|(key, value)| {
                    format!("--{} {:?}", key.to_lowercase().replace('_', "-"), value)
                })
                .collect::<Vec<_>>()
                .join(" ");
            println!("rabbitmq-mcp start {flags}");
        }
    }
    Ok(())
}

/// Prints a ready-to-use MCP client config (the `mcpServers` block a host
/// like Claude Code/Desktop expects) for whichever transport was selected
/// — the stdio and http shapes are mutually exclusive, never both, since
/// they're two different ways of running this same server and a client
/// only ever picks one. HTTP transport shows credentials as headers only
/// (never env/CLI args, matching `AuthManager::apply_auth_headers`'s
/// HTTP-only-uses-per-request-credentials behavior); stdio shows both the
/// `env` block and the equivalent all-CLI-args invocation, since the
/// config cascade accepts either for a spawned subprocess.
fn print_mcp_client_config(
    transport: Transport,
    auth_method: AuthMethod,
    env: &HashMap<String, String>,
) {
    match transport {
        Transport::Stdio => {
            let config = serde_json::json!({
                "mcpServers": {
                    "rabbitmq-mcp": {
                        "command": "rabbitmq-mcp",
                        "args": ["start"],
                        "env": env,
                    }
                }
            });
            println!("\nMCP client config (stdio):");
            println!("{}", serde_json::to_string_pretty(&config).unwrap());

            let cli_args = env
                .iter()
                .map(|(key, value)| format!("--{} {value:?}", key.to_lowercase().replace('_', "-")))
                .collect::<Vec<_>>()
                .join(" ");
            println!("(equivalently: `rabbitmq-mcp start {cli_args}`)");
        }
        Transport::Http => {
            let (_, header_name) =
                rabbitmq_mcp::auth::auth_manager::header_location_for(auth_method);
            let mut headers = serde_json::Map::new();
            headers.insert(
                header_name.to_string(),
                serde_json::Value::String("<credential value here>".to_string()),
            );
            let config = serde_json::json!({
                "mcpServers": {
                    "rabbitmq-mcp": {
                        "url": "http://127.0.0.1:3000/mcp",
                        "headers": headers,
                    }
                }
            });
            println!(
                "\nMCP client config (http) — adjust the host/port to match how you run \
                 `rabbitmq-mcp http`:"
            );
            println!("{}", serde_json::to_string_pretty(&config).unwrap());
            println!(
                "Credentials are never read from local config/env over HTTP transport — \
                 every request must carry its own \"{header_name}\" header."
            );
        }
    }
}

pub async fn run_setup_wizard() -> anyhow::Result<()> {
    let url = prompt_base_url().await?;
    let auth_method = prompt_auth_method().await?;
    let credentials = prompt_credentials(auth_method).await?;
    let api_version = prompt_api_version().await?;
    let transport = prompt_transport().await?;

    save_credential("active-credentials", &serde_json::to_string(&credentials)?)?;

    let auth_method_str = serde_json::to_value(auth_method)?
        .as_str()
        .unwrap_or_default()
        .to_string();
    let transport_str = serde_json::to_value(transport)?
        .as_str()
        .unwrap_or_default()
        .to_string();

    let mut env: HashMap<String, String> = HashMap::new();
    env.insert("RABBITMQ_MCP_URL".to_string(), url.clone());
    env.insert("RABBITMQ_MCP_AUTH_METHOD".to_string(), auth_method_str.clone());
    env.insert("RABBITMQ_MCP_API_VERSION".to_string(), api_version.clone());
    env.insert("RABBITMQ_MCP_TRANSPORT".to_string(), transport_str.clone());
    for (key, value) in &credentials {
        env.insert(format!("RABBITMQ_MCP_{}", to_env_key(key)), value.clone());
    }

    // Flat, unprefixed keys matching `config_manager::env_overrides`'s
    // `config_key` column — this is the shape `load_config`'s YAML layers
    // actually deserialize. Credentials are deliberately excluded (they
    // stay on the `save_credential` path only).
    let mut config_fields = Map::new();
    config_fields.insert("url".to_string(), Value::String(url));
    config_fields.insert("auth_method".to_string(), Value::String(auth_method_str));
    config_fields.insert("api_version".to_string(), Value::String(api_version));
    config_fields.insert("transport".to_string(), Value::String(transport_str));

    prompt_persistence(&config_fields, &env).await?;
    print_mcp_client_config(transport, auth_method, &env);

    let run_command = match transport {
        Transport::Stdio => "start",
        Transport::Http => "http",
    };
    println!("Setup complete! Run: rabbitmq-mcp {run_command}");
    Ok(())
}
