#!/usr/bin/env bash
# RabbitMQ Management HTTP API MCP server — generated by mcpify. Do not hand-edit.
# Steady-state heap profiling via dhat-rs. The generated search command starts
# DHAT after warmups so model initialization does not dominate measured work.
set -euo pipefail
cd "$(dirname "$0")/.."

# Catalog search does not call the generated API, but its shared config loader
# still requires these fields. Preserve explicit operator configuration and
# provide harmless local defaults for a fresh generated checkout.
export RABBITMQ_MCP_URL="${RABBITMQ_MCP_URL:-http://127.0.0.1}"

export RABBITMQ_MCP_AUTH_METHOD="${RABBITMQ_MCP_AUTH_METHOD:-basic}"


profile_query="${PROFILE_QUERY:-test query}"
profile_warmups="${PROFILE_HEAP_WARMUPS:-1}"
profile_iterations="${PROFILE_HEAP_ITERATIONS:-5}"

cargo run --release --features profiling --bin rabbitmq-mcp -- search "$profile_query" \
  --profile-warmups "$profile_warmups" \
  --profile-iterations "$profile_iterations"

echo
echo "Heap profile written to:"
echo "  dhat-heap.json (view at https://nnethercote.github.io/dh_view/dh_view.html)"
