// RabbitMQ Management HTTP API MCP server — generated by mcpify. Do not hand-edit.

use rusqlite::Connection;

use crate::data::store::search_endpoints;
use crate::services::embedding_service::embed;

/// Cheap diagnostic: warns (does not fail the search) when the active
/// store's `semantic_endpoints` table has fewer rows than `endpoints` —
/// a sign that `populate_embeddings` was run against an older/incomplete
/// state, so some operations can never surface as search results even
/// though they legitimately exist. Never changes the success/`[]`-results
/// contract for a query that just has no good semantic match.
fn warn_if_incomplete(conn: &Connection) {
    let counts: rusqlite::Result<(i64, i64)> = conn.query_row(
        "SELECT (SELECT COUNT(*) FROM endpoints), (SELECT COUNT(*) FROM semantic_endpoints)",
        [],
        |row| Ok((row.get(0)?, row.get(1)?)),
    );
    if let Ok((endpoints_count, semantic_count)) = counts
        && semantic_count < endpoints_count
    {
        tracing::warn!(
            endpoints_count,
            semantic_count,
            "semantic_endpoints is missing rows for this store — run populate-embeddings to \
             backfill; some operations will not surface in search results"
        );
    }
}

/// Semantic similarity lookup matching a natural-language query against
/// candidate API operations (PRD §1.5) — so an LLM never needs the full
/// OpenAPI spec in context to find the right operation.
pub fn search_operations(
    conn: &Connection,
    query: &str,
    limit: usize,
) -> anyhow::Result<serde_json::Value> {
    warn_if_incomplete(conn);
    let query_embedding = embed(query)?;
    let results = search_endpoints(conn, &query_embedding, limit)?;
    Ok(serde_json::to_value(results)?)
}
